/**
 *
 * @author yangfan
 * @since 2017/12/12 15:28
 *
 */
package com.panther.dboms

import com.panther.dboms.html.html
import com.panther.dboms.sql.select

fun main(args: Array<String>) {
    println(3.square())
    println(45.toHexString())
    val html = html {
        head {
            title {
                +"This page generated by kotlin dsl"
            }
            +"This is Head"
        }
        body {
            +"This is Body"
            b {
                +"tag b"
                a(href = "http://www.zhihu.com") {
                    +"tag b>a"
                }
            }
            p {
                +"tag p"
                a(href = "http://www.cnblogs.com") {
                    +"tag p>a"
                }
            }
            h1 {
                +"tag h1"
                a(href = "http://www.github.com") {
                    +"tag h1>a"
                }
            }
            a(href = "http://www.baidu.com") {
                +"tag body>a"
            }
        }
    }
    println(html)
    val sql = select {
        +"U.CREATED_BY"
        +"U.LAST_MODIFIED_BY"
        +"COUNT(U.DISPLAY_NAME) AS CT"
        from {
            +"BASE_USER U"
            +"BASE_ROLE R"
        }
        where {
            +"U.RID=R.ID"
            +"U.CREATED_BY=1"
        }
        groupby {
            +"U.CREATED_BY"
            +"U.LAST_MODIFIED_BY"
        }
        having {
            +"U.CREATED_BY=1"
            +"U.LAST_MODIFIED_BY=1"
        }
        orderby {
            +"U.CREATED_BY ASC"
            +"U.LAST_MODIFIED_BY DESC"
        }
    }
    println(sql)
}

fun Int.square(): Int = this * this

fun Int.toHexString(): String = Integer.toHexString(this)